crab submit submit_crab_DY.py
crab submit submit_crab_EGamma2017B.py
crab submit submit_crab_EGamma2017C.py
crab submit submit_crab_EGamma2017D.py
crab submit submit_crab_EGamma2017E.py
crab submit submit_crab_EGamma2017F.py
crab submit submit_crab_MuonEG2017B.py
crab submit submit_crab_MuonEG2017C.py
crab submit submit_crab_MuonEG2017D.py
crab submit submit_crab_MuonEG2017E.py
crab submit submit_crab_MuonEG2017F.py
crab submit submit_crab_ST_tW_antitop.py
crab submit submit_crab_ST_tW_top.py
crab submit submit_crab_ST_t_antitop.py
crab submit submit_crab_ST_t_top.py
crab submit submit_crab_SingleMuon2017B.py
crab submit submit_crab_SingleMuon2017C.py
crab submit submit_crab_SingleMuon2017D.py
crab submit submit_crab_SingleMuon2017E.py
crab submit submit_crab_SingleMuon2017F.py
crab submit submit_crab_TTTo2L2Nu.py
crab submit submit_crab_TTToHadronic.py
crab submit submit_crab_TTToSemiLeptonic.py
crab submit submit_crab_Tau2017B.py
crab submit submit_crab_Tau2017C.py
crab submit submit_crab_Tau2017D.py
crab submit submit_crab_Tau2017E.py
crab submit submit_crab_Tau2017F.py
crab submit submit_crab_W.py
crab submit submit_crab_W1.py
crab submit submit_crab_W2.py
crab submit submit_crab_W3.py
crab submit submit_crab_W4.py
crab submit submit_crab_WW2L2Nu.py
crab submit submit_crab_WZ2Q2L.py
crab submit submit_crab_WZ3LNu.py
crab submit submit_crab_ZZ2L2Nu.py
crab submit submit_crab_ZZ2L2Q.py
crab submit submit_crab_ZZ4L.py
